/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "krwbuybijxrqpandngfo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtyd2J1eWJpanhycXBhbmRuZ2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTUyOTcsImV4cCI6MjA2ODY3MTI5N30.iiO4EyYCdIv8-pH--YWLaYglXE5Crv2PqAe_2btPAtA"